- name: compare numbers
  hosts: localhost
  vars_prompt:
    name: number
    prompt: enter number
    private: no
  tasks:
  - name: number greate than 10
    ansible.builtin.debug:
      msg: "the enterd number is {{number}} greater than 10"
    when: number | int >=10

  - name: number is less than 10
    ansible.builtin.debug:
      msg: "the entered number is {{number}} less than 10"
    when: number | int <10