- name : install multiple servers
  hosts: localhost
  become: yes
  tasks:
  - name: install and start servers
    ansible.builtin.dnf:
      name: name.{{item}} 
      state: state.{{item}}
    loop:
    - {name="git", state="latest"}
    - {name="docker" state="obsent"}
