- name : install multiple servers
  hosts: localhost
  become: yes
  tasks:
  - name: install and start servers
    ansible.builtin.dnf:
      name: "{{item.name}}" 
      state: "{{item.state}}"
    loop:
    - { name= "git", state= "latest" }
    - { name= "docker", state= "latest" }
