- name: datatypes describe
  hosts: localhost
  vars:
    course: "AWS"
    Tools:
    - ec2
    - load balancer
    - route 53
    Experience:
      Devops: 2
      Aws: 2
      shell: 1
  tasks:
  - name: print the data types
    ansible.builtin.debug:
     msg: "i am jiong {{course}}, we are used {{Tools}}, and my having {{Experience}} "