- name: using coniditions create user
  hosts: web
  become: yes
  tasks:
  - name: check the user
    ansible.builtin.command: id sundar
      register: USER
  - name : print the user info
    ansible.builtlin.debug:
      msg: "user infor: {{USER}}"
    