- name: variables form prompt
  hosts: localhost
  vars_prompt:
    - name: username
      prompt: "Enter user name"
      private: no
  tasks:
  - name: prompt variable
    ansible.builtin.debug:
      msg: "The entered name is : {{NAME}}"