- name: using conditions
  hosts: web
  become: yes
  tasks:
  - name: check the user
    ansible.builtin.command: id sundar
    register: USER
    ignore_errors: True

  - name: print the user
    ansible.builtin.debug:
      msg: "user info is {{USER}}"
      
  - name: say hello
    ansible.builtin.debug:
      msg: "hi and hello"