- name : ping the servers
  hosts: web
  tasks:
  - name: ping the web  servers
    ansible.builtin.ping:
  - name: print the text on the console
    ansible.builtin.debug:
      msg: "this first ansible"