- name: variables in play
  hosts: localhost
  vars:
    course: "devops"
    trainer: "sundar"
    duration: "6 months"
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "the course is {{course}} and trainer is {{trainer}} for duration {{duration}}"
