- name: variable from files
  hosts: localhost
  vars_files:
  - variable-info.yml
  tasks:
  - name: print vaiables
    ansible.builtin.debug:
      msg: "my daughter name {{name}} and Age: {{age}} colour {{colour}}"
