- name: using args variable
  hosts: web
  vars:
    ansible_user: ec2-user
    ansible_password: DevOps321
  tasks:
  - name: print prompt variables
    ansible.builtin.debug:
      msg: "hello {{WISHES}}"